[package]
name = "nop-smart-contract"
version = "0.0.0"
authors = ["Yaron Wittenstein <yaron.wittenstein@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
panic = "abort"
opt-level = "z"
debug = false
